version: '3.1'

services:
  camera:
    image: public.ecr.aws/paia-tech/your_package:latest
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
    network_mode: host
    privileged: true
    # TODO connect the device you need
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    command: ros2 launch your_package
